const API=window.APP_CONFIG?.API_URL||'/api/race';
let state={race:null,loops:[],reminders:[],plan:[],notes:JSON.parse(localStorage.getItem('backyardNotes')||'[]'),gear:JSON.parse(localStorage.getItem('backyardGear')||'[]')};
const $=id=>document.getElementById(id);const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};const width=(id,v)=>{const e=$(id);if(e)e.style.width=v};let activeTab='liveTab';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showError(e){console.error(e);const x=$('error');if(x){x.textContent=e.message||String(e);x.classList.remove('hidden')}}
async function api(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw Error(d.error||`Request failed (${r.status})`);return d}
async function load(){try{set('syncStatus','SYNCING');state={...state,...await api('getAll')};render();set('syncStatus','LIVE')}catch(e){showError(e)}}
function timeKey(v){const m=String(v||'').trim().toUpperCase().match(/(\d{1,2})(?::(\d{2}))?\s*(AM|PM)?/);if(!m)return 999999;let h=+m[1],n=+(m[2]||0);if(m[3]==='PM'&&h<12)h+=12;if(m[3]==='AM'&&h===12)h=0;return h*60+n}
function planSort(a,b){const fa=a.fields||{},fb=b.fields||{},da=fa.Date||'9999-12-31',db=fb.Date||'9999-12-31';return da!==db?da.localeCompare(db):timeKey(fa.Time)-timeKey(fb.Time)}
function fmtShort(s){s=Math.max(0,Math.floor(s));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function render(){const f=state.race?.fields||{},start=f['Start Time']?new Date(f['Start Time']):null,status=f.Status||'Not Started',stored=Number(f['Current Loop']||1),dist=Number(f['Loop Distance']||4.167);let current=stored;if(status==='Running'&&start)current=Math.max(stored,Math.floor((Date.now()-start)/3600000)+1);const miles=(current-1)*dist;set('raceTitle',f['Race Name']||'Backyard Ultra');set('currentLoop',current);set('runnerLoop',current);set('miles',miles.toFixed(1));set('raceStatus',status.toUpperCase());set('heroLoop',`LOOP ${current}`);
const vals=state.loops.map(loopMinutes).filter(v=>v!=null),last=vals.length?vals[vals.length-1]:null;set('lastLoop',last!=null?`${last.toFixed(0)} MIN`:'—');let remaining=0;if(status==='Running'&&start){remaining=Math.max(0,Math.floor((start.getTime()+current*3600000-Date.now())/1000));set('countdown',fmtShort(remaining));set('runnerCountdown',fmtShort(remaining));width('raceProgress',Math.min(100,Math.max(0,(3600-remaining)/36))+'%');set('elapsedProgress',fmtShort(3600-remaining)+' elapsed');set('remainingProgress',fmtShort(remaining)+' remaining')}else{set('countdown',status==='Finished'?'DONE':status==='DNF'?'DNF':'42:17');set('runnerCountdown','42:17');width('raceProgress','0%');set('elapsedProgress','— elapsed');set('remainingProgress','42:17 remaining')}
const elapsed=start?Math.max(0,Math.floor((Date.now()-start)/60000)):0;set('elapsed',start?`${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')}`:'—');renderPhase(status,remaining);renderPlan();renderReminders();renderLoops();renderNotes();renderGear();renderMilestones(current,dist);calcPace()}
function renderPhase(status,remaining){let title='RACE READY',meta='Food · Fluids · Gear · Check In';if(status==='Finished'){title='RACE COMPLETE';meta='You did the work.'}else if(status==='DNF'){title='RACE STOPPED';meta='Race marked DNF.'}else if(status==='Running'){if(remaining<300){title='BELL IN '+fmtShort(remaining);meta='Final checks · Get to the line'}else if(remaining<600){title='GET CREW READY';meta='Food · Fluids · Gear · Check In'}else if(remaining<1200){title='CREW STANDBY';meta='Watch clock · Prep next kit'}}set('phaseTitle',title);set('phaseMeta',meta);const c=$('phaseCard');if(c)c.className='phase-card'+(remaining<600&&status==='Running'?' urgent':'')}
function renderPlan(){const el=$('planList');if(!el)return;el.innerHTML='';const items=[...state.plan].sort(planSort);let last='';items.forEach(x=>{const f=x.fields||{},done=f.Done===true||f.Status==='Done',key=f.Date||'No date';if(key!==last){const h=document.createElement('div');h.className='day-heading';h.textContent=f.Date?new Date(f.Date+'T00:00:00').toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'}):'No date';el.appendChild(h);last=key}const row=document.createElement('div');row.className='planRow';row.innerHTML=`<div class="planMain ${done?'done':''}"><b>${esc(f.Name||f.Item||'Plan item')}</b><div class="muted">${esc(f.Time||'')} ${f['Loop #']?`· Loop ${esc(f['Loop #'])}`:''} ${f.Category?`· ${esc(f.Category)}`:''}</div></div><button>${done?'Undo':'Done'}</button>`;row.querySelector('button').onclick=async()=>{try{await api('setPlanDone',{id:x.id,done:!done});await load()}catch(e){showError(e)}};el.appendChild(row)});set('nextPlan',items.find(x=>x.fields?.Done!==true&&x.fields?.Status!=='Done')?.fields?.Name||'Nothing pending');const p=items.find(x=>x.fields?.Done!==true&&x.fields?.Status!=='Done');set('nextMeta',p?`${p.fields?.Time||''}${p.fields?.['Loop #']?` · Loop ${p.fields['Loop #']}`:''}`:'')}
function renderReminders(){const el=$('reminderList');if(!el)return;el.innerHTML='';if(!state.reminders.length){el.innerHTML='<div class="muted">No reminders yet.</div>';return}state.reminders.forEach(x=>{const f=x.fields||{},done=f.Done===true,row=document.createElement('div');row.className='reminderRow';row.innerHTML=`<div class="planMain ${done?'done':''}"><b>${esc(f.Reminder||'Reminder')}</b><div class="muted">${esc(f.Type||'')} ${f.Interval?`· every ${esc(f.Interval)}`:''} ${f['Next Due']?`· due ${esc(f['Next Due'])}`:''}</div></div><button>${done?'Undo':'Done'}</button>`;row.querySelector('button').onclick=async()=>{try{await api('setReminderDone',{id:x.id,done:!done});await load()}catch(e){showError(e)}};el.appendChild(row)})}
function loopMinutes(x){const m=String(x.fields?.['Loop Time']||'').match(/([0-9]+(?:\.[0-9]+)?)/);return m?Number(m[1]):null}
function renderLoops(){const el=$('loopList');if(!el)return;el.innerHTML='';const vals=state.loops.map(loopMinutes).filter(v=>v!=null);set('avgLoop',vals.length?`${(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1)} min`:'—');set('fastestLoop',vals.length?`${Math.min(...vals)} min`:'—');set('slowestLoop',vals.length?`${Math.max(...vals)} min`:'—');if(!state.loops.length){el.innerHTML='<div class="muted">No completed loops recorded yet.</div>';return}[...state.loops].reverse().slice(0,50).forEach(x=>{const f=x.fields||{},row=document.createElement('div');row.className='loopRow';row.innerHTML=`<div class="planMain"><b>Loop ${esc(f['Loop #']||'')}</b><div class="muted">${f['Loop Time']?`Time: ${esc(f['Loop Time'])}`:''}</div></div><b>${Number(f['Total Miles']||0).toFixed(1)} mi</b>`;el.appendChild(row)})}
function renderMilestones(current,dist){const el=$('milestoneList');if(!el)return;const ms=[25,50,75,100];el.innerHTML=ms.map(m=>{const hit=(current-1)*dist>=m;return `<div class="milestone ${hit?'hit':''}"><b>${m}</b><span>MI</span><i>${hit?'✓':''}</i></div>`}).join('');const n=ms.find(m=>(current-1)*dist<m);set('milestoneNext',n?`${n} mi next`:'100+ mi')}
function renderGear(){const el=$('gearList');if(!el)return;el.innerHTML='';state.gear.slice().sort((a,b)=>(Number(a.loop)||999)-(Number(b.loop)||999)).forEach(g=>{const row=document.createElement('div');row.className='gearRow';row.innerHTML=`<div class="gearIcon">${g.type==='Shoes'?'👟':g.type==='Socks'?'🧦':'▣'}</div><div class="planMain"><b>${esc(g.item)}</b><div class="muted">${esc(g.type)} ${g.loop?`· Loop ${esc(g.loop)}`:''}</div></div><button>${g.done?'Undo':'USED'}</button>`;row.querySelector('button').onclick=()=>{g.done=!g.done;localStorage.setItem('backyardGear',JSON.stringify(state.gear));renderGear()};el.appendChild(row)});const cur=$('currentGear');if(cur){cur.innerHTML='';const active=state.gear.filter(g=>!g.done);if(!active.length){cur.innerHTML='<div class="muted">Add the current kit above.</div>'}else active.slice(0,5).forEach(g=>{const d=document.createElement('div');d.className='current-gear';d.innerHTML=`<b>${esc(g.item)}</b><span>${esc(g.type)}</span>`;cur.appendChild(d)})}}
function renderNotes(){const el=$('noteList');if(el)el.innerHTML=state.notes.slice(-30).reverse().map(x=>`<div class="muted" style="padding:9px 0;border-top:1px solid #1c304b">${esc(x)}</div>`).join('')}
function calcPace(){const min=Math.max(1,Number($('paceMinutes')?.value)||60),dist=Math.max(.1,Number($('paceDistance')?.value)||4.167),sec=Math.round(min/dist*60),mph=dist/(min/60);set('pacePerMile',`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`);set('paceMph',mph.toFixed(2));set('paceLoopTime',`${Math.floor(min)}:${String(Math.round((min-Math.floor(min))*60)%60).padStart(2,'0')}`)}
function addNote(v){state.notes.push(new Date().toLocaleTimeString()+' — '+v);localStorage.setItem('backyardNotes',JSON.stringify(state.notes));renderNotes()}
function switchTab(tab){activeTab=tab;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===tab));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('menuBtn')?.addEventListener('click',()=>switchTab('crewTab'));$('modeBtn')?.addEventListener('click',()=>switchTab('runnerTab'));document.querySelectorAll('#paceMinutes,#paceDistance').forEach(x=>x.addEventListener('input',calcPace));document.querySelectorAll('[data-pace]').forEach(b=>b.addEventListener('click',()=>{$('paceMinutes').value=b.dataset.pace;calcPace()}));$('saveNoteBtn')?.addEventListener('click',()=>{const v=$('noteInput').value.trim();if(v){addNote(v);$('noteInput').value=''}});$('resetCheckBtn')?.addEventListener('click',()=>document.querySelectorAll('[data-check]').forEach(b=>b.classList.remove('checked')));document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>b.classList.toggle('checked'));$('goodGoBtn')?.addEventListener('click',()=>{addNote('Runner: quick check complete — good to go');switchTab('liveTab')});
$('startBtn')?.addEventListener('click',async()=>{if(!confirm('Start the race now?'))return;try{await api('startRace');await load();switchTab('liveTab')}catch(e){showError(e)}});$('resetBtn')?.addEventListener('click',async()=>{if(!confirm('Reset race to NOT STARTED?'))return;try{await api('resetRace');await load()}catch(e){showError(e)}});$('completeBtn')?.addEventListener('click',async()=>{if(!confirm('Mark the current loop complete?'))return;try{await api('completeLoop');await load()}catch(e){showError(e)}});$('dnfBtn')?.addEventListener('click',async()=>{if(confirm('Mark the race DNF?'))try{await api('setStatus',{status:'DNF'});await load()}catch(e){showError(e)}});$('finishBtn')?.addEventListener('click',async()=>{if(confirm('Mark the race finished?'))try{await api('setStatus',{status:'Finished'});await load()}catch(e){showError(e)}});
$('addPlanBtn')?.addEventListener('click',()=>$('planDialog').showModal());$('planForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('createPlan',{fields:{Date:f.get('date'),Time:f.get('time'),Name:f.get('name'),'Loop #':f.get('loop')?Number(f.get('loop')):null,Item:f.get('item'),Category:f.get('category'),Status:'Not started',Notes:f.get('notes'),Done:false}});e.target.reset();$('planDialog').close();await load()}catch(x){showError(x)}});$('addReminderBtn')?.addEventListener('click',()=>$('reminderDialog').showModal());$('reminderForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('createReminder',{fields:{Reminder:f.get('reminder'),Type:f.get('type'),Interval:f.get('interval')?Number(f.get('interval')):null,'Next Due':f.get('nextDue'),Notes:f.get('notes'),Done:false}});e.target.reset();$('reminderDialog').close();await load()}catch(x){showError(x)}});$('addGearBtn')?.addEventListener('click',()=>$('gearDialog').showModal());$('gearForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.gear.push({item:f.get('item'),type:f.get('type'),loop:f.get('loop')?Number(f.get('loop')):null,notes:f.get('notes'),done:false});localStorage.setItem('backyardGear',JSON.stringify(state.gear));e.target.reset();$('gearDialog').close();renderGear()});
render();load();setInterval(()=>{if(state.race)render()},1000);
