/* Stable live race refinements. Update only existing elements; never rebuild cards on the clock tick. */
(function(){
  const qs=s=>document.querySelector(s);
  const fmtTime=sec=>{sec=Math.max(0,Math.round(sec));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s2=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s2).padStart(2,'0')}`:`${m}:${String(s2).padStart(2,'0')}`};
  const parseTime=v=>{const m=String(v||'').match(/(\d+)\s*:\s*(\d+)(?::(\d+))?/);if(!m)return null;return m[3]?Number(m[1])*3600+Number(m[2])*60+Number(m[3]):Number(m[1])*60+Number(m[2]);};
  let remote={race:null,loops:[]};
  const refreshRemote=async()=>{try{const r=await fetch('/api/race',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'getAll'})});if(!r.ok)return;remote=await r.json();updateStatic();}catch(e){}};
  const raceFields=()=>remote.race?.fields||{};
  const getTiming=()=>{const r=raceFields(),start=r['Start Time']?new Date(r['Start Time']):null,status=r.Status||'Not Started';if(!start||status!=='Running')return {status,start,loop:Number(r['Current Loop']||1),remaining:0};const loop=Math.max(Number(r['Current Loop']||1),Math.floor((Date.now()-start.getTime())/3600000)+1);const remaining=Math.max(0,Math.floor((start.getTime()+loop*3600000-Date.now())/1000));return {status,start,loop,remaining};};
  const updateWarning=()=>{const card=qs('.race-card');if(!card)return;card.classList.remove('warn3','warn2','warn1');const t=getTiming();if(t.status!=='Running')return;if(t.remaining>0&&t.remaining<=60)card.classList.add('warn1');else if(t.remaining<=120)card.classList.add('warn2');else if(t.remaining<=180)card.classList.add('warn3');};
  const sortedLoops=()=>Array.isArray(remote.loops)?remote.loops.slice().sort((a,b)=>Number(a.fields?.['Loop #']||0)-Number(b.fields?.['Loop #']||0)):[];
  const updateLastLoop=()=>{const loops=sortedLoops();if(!loops.length)return;const f=loops[loops.length-1]?.fields||{},sec=parseTime(f['Loop Time']);if(sec!=null){const el=qs('#lastLoop');if(el)el.textContent=`${fmtTime(sec)} (${fmtTime(Math.round(sec/4.167))}/mi)`;}};
  const updateInbound=()=>{const home=qs('#liveTab');if(!home)return;const t=getTiming();let card=qs('#runnerInboundCard');if(t.status!=='Running'){if(card)card.remove();return;}if(!card){card=document.createElement('section');card.id='runnerInboundCard';card.className='card inbound-card';const anchor=qs('.phase-card');if(anchor)anchor.parentNode.insertBefore(card,anchor.nextSibling);else home.appendChild(card);}const loops=sortedLoops(),lastF=loops[loops.length-1]?.fields||{},lastSec=parseTime(lastF['Loop Time']),remaining=t.remaining;let title='RUNNER OUT',meta=`Loop ${t.loop} underway`,ret='EXPECTED RETURN',retVal=lastSec!=null?`~${fmtTime(lastSec)}`:'Before the next bell';if(remaining<=180){title='RUNNER INBOUND';meta=remaining<=60?'Get to the corral. Final minute.':`Loop ${t.loop} ends soon. Get the next kit ready.`;ret='NEXT BELL';retVal=fmtTime(remaining);}card.innerHTML=`<div class="inbound-icon">↗</div><div><div class="section-kicker">${title}</div><b>${meta}</b><small><span>${ret}</span><strong>${retVal}</strong></small></div><div class="inbound-kit"><i>🥤</i><i>🍌</i><i>🧦</i><i>👕</i></div>`;};
  const updateNight=()=>{const home=qs('#liveTab');if(!home)return;const t=getTiming();let card=qs('#nightAlertCard');if(t.status!=='Running'||t.loop<10){if(card)card.remove();return;}if(!card){card=document.createElement('section');card.id='nightAlertCard';card.className='card night-alert-card';const anchor=qs('#runnerInboundCard')||qs('.phase-card');if(anchor)anchor.parentNode.insertBefore(card,anchor.nextSibling);else home.appendChild(card);}card.innerHTML=`<div class="night-alert-icon">☾</div><div><div class="section-kicker">${t.loop===10?'NIGHT GEAR REQUIRED':'NIGHT GEAR CHECK'}</div><b>Lights + high-vis stay on.</b><small>Headlamp · reflective gear · high-vis layer</small></div>`;};
  const updateHome=()=>{const next=qs('.next-card');if(next&&!next.dataset.bound){next.dataset.bound='1';next.setAttribute('role','button');next.setAttribute('tabindex','0');const go=()=>{if(typeof window.switchTab==='function'){window.switchTab('planTab');setTimeout(()=>qs('#planList .planRow')?.scrollIntoView({behavior:'smooth',block:'center'}),80);}};next.addEventListener('click',go);next.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}});}};
  const updateStatic=()=>{updateWarning();updateLastLoop();updateInbound();updateNight();updateHome();};
  window.addEventListener('load',()=>{updateStatic();refreshRemote();setInterval(updateStatic,1000);setInterval(refreshRemote,10000);});
})();
