const API=window.APP_CONFIG?.API_URL||'/api/race';
let state={race:null,loops:[],reminders:[],plan:[],notes:JSON.parse(localStorage.getItem('backyardNotes')||'[]'),gear:JSON.parse(localStorage.getItem('backyardGear')||'[]')};
const $=id=>document.getElementById(id);let activeTab='liveTab';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showError(e){console.error(e);const el=$('error');if(el){el.textContent=e.message||String(e);el.classList.remove('hidden')} }
async function api(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw Error(d.error||`Request failed (${r.status})`);return d}
async function load(){try{const el=$('syncStatus');if(el)el.textContent='SYNCING';state={...state,...await api('getAll')};render();if(el)el.textContent='LIVE'}catch(e){showError(e)}}
function timeKey(v){const m=String(v||'').trim().toUpperCase().match(/(\d{1,2})(?::(\d{2}))?\s*(AM|PM)?/);if(!m)return 999999;let h=+m[1],n=+(m[2]||0);if(m[3]==='PM'&&h<12)h+=12;if(m[3]==='AM'&&h===12)h=0;return h*60+n}
function planSort(a,b){const fa=a.fields||{},fb=b.fields||{},da=fa.Date||'9999-12-31',db=fb.Date||'9999-12-31';return da!==db?da.localeCompare(db):timeKey(fa.Time)-timeKey(fb.Time)}
function fmtClock(sec){sec=Math.max(0,Math.floor(sec));return [Math.floor(sec/3600),Math.floor(sec%3600/60),sec%60].map(n=>String(n).padStart(2,'0')).join(':')}
function render(){const f=state.race?.fields||{},start=f['Start Time']?new Date(f['Start Time']):null,status=f.Status||'Not Started',stored=Number(f['Current Loop']||1),dist=Number(f['Loop Distance']||4.167);let current=stored;if(status==='Running'&&start)current=Math.max(stored,Math.floor((Date.now()-start)/3600000)+1);const miles=(current-1)*dist;
$('raceTitle')?.textContent=f['Race Name']||'Backyard Ultra';$('currentLoop')?.textContent=current;$('runnerLoop')?.textContent=current;$('miles')?.textContent=miles.toFixed(1);$('raceStatus')?.textContent=status.toUpperCase();$('heroLoop')?.textContent=`LOOP ${current}`;
const vals=state.loops.map(loopMinutes).filter(v=>v!=null),last=vals.length?vals[vals.length-1]:null;const lastText=last!=null?`${last.toFixed(0)} MIN`: '—';$('lastLoop')?.textContent=lastText;
let remaining=0;if(status==='Running'&&start){remaining=Math.max(0,Math.floor((start.getTime()+current*3600000-Date.now())/1000));$('countdown')?.textContent=fmtShort(remaining);$('runnerCountdown')?.textContent=fmtShort(remaining);const pct=Math.min(100,Math.max(0,(3600-remaining)/36));$('raceProgress')?.style.setProperty('width',pct+'%');$('elapsedProgress')?.textContent=fmtShort(3600-remaining)+' elapsed';$('remainingProgress')?.textContent=fmtShort(remaining)+' remaining'}else{$('countdown')?.textContent=status==='Finished'?'DONE':status==='DNF'?'DNF':'42:17';$('runnerCountdown')?.textContent='42:17';$('raceProgress')?.style.setProperty('width','0%');$('elapsedProgress')?.textContent='— elapsed';$('remainingProgress')?.textContent='— remaining'}
const elapsed=start?Math.max(0,Math.floor((Date.now()-start)/60000)):0;$('elapsed')?.textContent=start?`${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')}`:'—';
renderPhase(status,remaining);renderPlan();renderReminders();renderLoops();renderNotes();renderGear();renderMilestones(current,dist);calcPace()}
function fmtShort(sec){sec=Math.max(0,Math.floor(sec));return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function renderPhase(status,remaining){let title='RACE READY',meta='Food · Fluids · Gear · Check In';if(status==='Finished'){title='RACE COMPLETE';meta='You did the work.'}else if(status==='DNF'){title='RACE STOPPED';meta='Race marked DNF.'}else if(status==='Running'){if(remaining<300){title='BELL IN '+fmtShort(remaining);meta='Final checks · Get to the line'}else if(remaining<600){title='GET CREW READY';meta='Food · Fluids · Gear · Check In'}else if(remaining<1200){title='CREW STANDBY';meta='Watch clock · Prep next kit'}else{title='RACE READY';meta='Food · Fluids · Gear · Check In'}}$('phaseTitle')?.textContent=title;$('phaseMeta')?.textContent=meta;const c=$('phaseCard');if(c)c.className='phase-card'+(remaining<600&&status==='Running'?' urgent':'')}
function renderPlan(){const el=$('planList');if(!el)return;el.innerHTML='';const items=[...state.plan].sort(planSort);let last='';items.forEach(x=>{const f=x.fields||{},done=f.Done===true||f.Status==='Done',key=f.Date||'No date';if(key!==last){const h=document.createElement('div');h.className='day-heading';h.textContent=f.Date?new Date(f.Date+'T00:00:00').toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'}):'No date';el.appendChild(h);last=key}const row=document.createElement('div');row.className='planRow';row.innerHTML=`<div class="planMain ${done?'done':''}"><b>${esc(f.Name||f.Item||'Plan item')}</b><div class="muted">${esc(f.Time||'')} ${f['Loop #']?`· Loop ${esc(f['Loop #'])}`:''} ${f.Category?`· ${esc(f.Category)}`:''}</div></div><button>${done?'Undo':'Done'}</button>`;row.querySelector('button').onclick=async()=>{try{await api('setPlanDone',{id:x.id,done:!done});await load()}catch(e){showError(e)}};el.appendChild(row)});const p=items.find(x=>x.fields?.Done!==true&&x.fields?.Status!=='Done');$('nextPlan')?.replaceChildren(document.createTextNode(p?`${p.fields?.Name||p.fields?.Item||'Next item'}`:'Nothing pending'));$('nextMeta')?.replaceChildren(document.createTextNode(p?`${p.fields?.Time||''}${p.fields?.['Loop #']?` · Loop ${p.fields['Loop #']}`:''}`:''))}
function renderReminders(){const el=$('reminderList');if(!el)return;el.innerHTML='';if(!state.reminders.length){el.innerHTML='<div class="muted">No reminders yet.</div>';return}state.reminders.forEach(x=>{const f=x.fields||{},done=f.Done===true,row=document.createElement('div');row.className='reminderRow';row.innerHTML=`<div class="planMain ${done?'done':''}"><b>${esc(f.Reminder||'Reminder')}</b><div class="muted">${esc(f.Type||'')} ${f.Interval?`· every ${esc(f.Interval)}`:''} ${f['Next Due']?`· due ${esc(f['Next Due'])}`:''}</div></div><button>${done?'Undo':'Done'}</button>`;row.querySelector('button').onclick=async()=>{try{await api('setReminderDone',{id:x.id,done:!done});await load()}catch(e){showError(e)}};el.appendChild(row)})}
function loopMinutes(x){const s=String(x.fields?.['Loop Time']||'').match(/([0-9]+(?:\.[0-9]+)?)/);return s?Number(s[1]):null}
function renderLoops(){const el=$('loopList');if(!el)return;el.innerHTML='';const vals=state.loops.map(loopMinutes).filter(v=>v!=null);$('avgLoop')?.textContent=vals.length?`${(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1)} min`:'—';$('fastestLoop')?.textContent=vals.length?`${Math.min(...vals)} min`:'—';$('slowestLoop')?.textContent=vals.length?`${Math.max(...vals)} min`:'—';if(!state.loops.length){el.innerHTML='<div class="muted">No completed loops recorded yet.</div>';return}[...state.loops].reverse().slice(0,50).forEach(x=>{const f=x.fields||{},row=document.createElement('div');row.className='loopRow';row.innerHTML=`<div class="planMain"><b>Loop ${esc(f['Loop #']||'')}</b><div class="muted">${f['Loop Time']?`Time: ${esc(f['Loop Time'])}`:''}</div></div><b>${Number(f['Total Miles']||0).toFixed(1)} mi</b>`;el.appendChild(row)})}
function renderMilestones(current,dist){const el=$('milestoneList');if(!el)return;const ms=[25,50,75,100];el.innerHTML=ms.map(m=>{const hit=(current-1)*dist>=m;return `<div class="milestone ${hit?'hit':''}"><b>${m}</b><span>MI</span><i>${hit?'✓':''}</i></div>`}).join('');$('milestoneNext')?.textContent=(ms.find(m=>(current-1)*dist<m)||'100+')+' mi next'}
function renderGear(){const el=$('gearList');if(!el)return;el.innerHTML='';state.gear.slice().sort((a,b)=>(Number(a.loop)||999)-(Number(b.loop)||999)).forEach(g=>{const row=document.createElement('div');row.className='gearRow';row.innerHTML=`<div class="gearIcon">${g.type==='Shoes'?'👟':g.type==='Socks'?'🧦':'▣'}</div><div class="planMain"><b>${esc(g.item)}</b><div class="muted">${esc(g.type)} ${g.loop?`· Loop ${esc(g.loop)}`:''}</div></div><button>${g.done?'Undo':'USED'}</button>`;row.querySelector('button').onclick=()=>{g.done=!g.done;localStorage.setItem('backyardGear',JSON.stringify(state.gear));renderGear()};el.appendChild(row)});const active=state.gear.filter(g=>!g.done);$('currentGear')?.replaceChildren(...(active.length?active.slice(0,5).map(g=>{const d=document.createElement('div');d.className='current-gear';d.innerHTML=`<b>${esc(g.item)}</b><span>${esc(g.type)}</span>`;return d}):[Object.assign(document.createElement('div'),{className:'muted',textContent:'Add the current kit above.'})]))}
function renderNotes(){const el=$('noteList');if(!el)return;el.innerHTML=state.notes.slice(-30).reverse().map(x=>`<div class="muted" style="padding:9px 0;border-top:1px solid #1c304b">${esc(x)}</div>`).join('')}
function calcPace(){const min=Math.max(0,Number($('paceMinutes')?.value)||60),dist=Math.max(.1,Number($('paceDistance')?.value)||4.167);const sec=Math.round(min/dist*60),mph=dist/(min/60);$('pacePerMile')?.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;$('paceMph')?.textContent=mph.toFixed(2);$('paceLoopTime')?.textContent=`${Math.floor(min)}:${String(Math.round((min-Math.floor(min))*60)%60).padStart(2,'0')}`}
function addNote(v){const s=new Date().toLocaleTimeString()+' — '+v;state.notes.push(s);localStorage.setItem('backyardNotes',JSON.stringify(state.notes));renderNotes()}
function switchTab(tab){activeTab=tab;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===tab));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('menuBtn')?.addEventListener('click',()=>switchTab('crewTab'));$('modeBtn')?.addEventListener('click',()=>switchTab('runnerTab'));document.querySelectorAll('#paceMinutes,#paceDistance').forEach(x=>x.addEventListener('input',calcPace));document.querySelectorAll('[data-pace]').forEach(b=>b.addEventListener('click',()=>{$('paceMinutes').value=b.dataset.pace;calcPace()}));
$('saveNoteBtn')?.addEventListener('click',()=>{const v=$('noteInput').value.trim();if(v){addNote(v);$('noteInput').value=''}});$('resetCheckBtn')?.addEventListener('click',()=>document.querySelectorAll('[data-check]').forEach(b=>b.classList.remove('checked')));document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>b.classList.toggle('checked'));$('goodGoBtn')?.addEventListener('click',()=>{addNote('Runner: quick check complete — good to go');switchTab('liveTab')});
$('startBtn')?.addEventListener('click',async()=>{if(!confirm('Start the race now?'))return;try{await api('startRace');await load();switchTab('liveTab')}catch(e){showError(e)}});$('resetBtn')?.addEventListener('click',async()=>{if(!confirm('Reset race to NOT STARTED?'))return;try{await api('resetRace');await load()}catch(e){showError(e)}});$('completeBtn')?.addEventListener('click',async()=>{if(!confirm('Mark the current loop complete?'))return;try{await api('completeLoop');await load()}catch(e){showError(e)}});$('dnfBtn')?.addEventListener('click',async()=>{if(confirm('Mark the race DNF?'))try{await api('setStatus',{status:'DNF'});await load()}catch(e){showError(e)}});$('finishBtn')?.addEventListener('click',async()=>{if(confirm('Mark the race finished?'))try{await api('setStatus',{status:'Finished'});await load()}catch(e){showError(e)}});
$('addPlanBtn')?.addEventListener('click',()=>$('planDialog').showModal());$('planForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('createPlan',{fields:{Date:f.get('date'),Time:f.get('time'),Name:f.get('name'), 'Loop #':f.get('loop')?Number(f.get('loop')):null,Item:f.get('item'),Category:f.get('category'),Status:'Not started',Notes:f.get('notes'),Done:false}});e.target.reset();$('planDialog').close();await load()}catch(x){showError(x)}});$('addReminderBtn')?.addEventListener('click',()=>$('reminderDialog').showModal());$('reminderForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('createReminder',{fields:{Reminder:f.get('reminder'),Type:f.get('type'),Interval:f.get('interval')?Number(f.get('interval')):null,'Next Due':f.get('nextDue'),Notes:f.get('notes'),Done:false}});e.target.reset();$('reminderDialog').close();await load()}catch(x){showError(x)}});$('addGearBtn')?.addEventListener('click',()=>$('gearDialog').showModal());$('gearForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.gear.push({item:f.get('item'),type:f.get('type'),loop:f.get('loop')?Number(f.get('loop')):null,notes:f.get('notes'),done:false});localStorage.setItem('backyardGear',JSON.stringify(state.gear));e.target.reset();$('gearDialog').close();renderGear()});
render();calcPace();load();setInterval(()=>{if(state.race)render()},1000);
