const API=window.APP_CONFIG?.API_URL||"/api/race";let state={race:null,loops:[],reminders:[],plan:[],notes:JSON.parse(localStorage.getItem("backyardNotes")||"[]")};const $=id=>document.getElementById(id);let activeTab="liveTab";
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function showError(e){console.error(e);$("error").textContent=e.message||String(e);$("error").classList.remove("hidden");$("syncStatus").textContent="Connection error"}
async function api(action,payload={}){const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw Error(d.error||`Request failed (${r.status})`);return d}
async function load(){try{$("syncStatus").textContent="Syncing…";state={...state,...await api("getAll")};render();$("syncStatus").textContent="Synced";$("lastUpdated").textContent="Updated "+new Date().toLocaleTimeString()}catch(e){showError(e)}}
function timeKey(v){const s=String(v||"").trim().toUpperCase(),m=s.match(/(\d{1,2})(?::(\d{2}))?\s*(AM|PM)?/);if(!m)return 999999;let h=Number(m[1]),min=Number(m[2]||0);if(m[3]==="PM"&&h<12)h+=12;if(m[3]==="AM"&&h===12)h=0;return h*60+min}
function planSort(a,b){const fa=a.fields||{},fb=b.fields||{},da=fa.Date||"9999-12-31",db=fb.Date||"9999-12-31";if(da!==db)return da.localeCompare(db);return timeKey(fa.Time)-timeKey(fb.Time)}
function render(){const r=state.race,f=r?.fields||{},start=f["Start Time"]?new Date(f["Start Time"]):null,status=f.Status||"Not Started",stored=Number(f["Current Loop"]||1),dist=Number(f["Loop Distance"]||4.1);let current=stored;if(status==="Running"&&start)current=Math.max(stored,Math.floor((Date.now()-start)/3600000)+1);$("raceTitle").textContent=f["Race Name"]||"Backyard Ultra";$("currentLoop").textContent=current;$("miniLoop").textContent=current;$("miles").textContent=((current-1)*dist).toFixed(1);$("miniMiles").textContent=((current-1)*dist).toFixed(1);$("raceStatus").textContent=status.toUpperCase();$("lastLoop").textContent=state.loops.length?(state.loops[state.loops.length-1].fields?.["Loop Time"]||"—"):"—";if(start){const mm=Math.max(0,Math.floor((Date.now()-start)/60000));$("elapsed").textContent=`${Math.floor(mm/60)}h ${mm%60}m`}else $("elapsed").textContent="—";if(status==="Running"&&start){let sec=Math.max(0,Math.floor((start.getTime()+current*3600000-Date.now())/1000));const cd=[Math.floor(sec/3600),Math.floor(sec%3600/60),sec%60].map(n=>String(n).padStart(2,"0")).join(":");$("countdown").textContent=cd;$("miniCountdown").textContent=cd}else{const cd=status==="Finished"?"DONE":status==="DNF"?"DNF":"--:--:--";$("countdown").textContent=cd;$("miniCountdown").textContent=cd}renderPlan();renderReminders();renderLoops();renderNotes()}
function renderPlan(){const el=$("planList");el.innerHTML="";const items=[...state.plan].sort(planSort);let last="";items.forEach(x=>{const f=x.fields||{},done=f.Done===true||f.Status==="Done",date=f.Date?new Date(f.Date+"T00:00:00"):null,key=f.Date||"No date";if(key!==last){const h=document.createElement("div");h.className="day-heading";h.textContent=date?date.toLocaleDateString([], {weekday:"long",month:"short",day:"numeric"}):"No date";el.appendChild(h);last=key}const row=document.createElement("div");row.className="planRow";row.innerHTML=`<div class="planMain ${done?"done":""}"><b>${esc(f.Name||f.Item||"Plan item")}</b><div class="muted">${esc(f.Time||"")} ${f["Loop #"]?`· Loop ${esc(f["Loop #"])}`:""} ${f.Category?`· ${esc(f.Category)}`:""}</div>${f.Notes?`<div class="muted">${esc(f.Notes)}</div>`:""}</div><button class="small">${done?"Undo":"Done"}</button>`;row.querySelector("button").onclick=async()=>{try{await api("setPlanDone",{id:x.id,done:!done});await load()}catch(e){showError(e)}};el.appendChild(row)});const pending=items.find(x=>x.fields?.Done!==true&&x.fields?.Status!=="Done");$("nextPlan").textContent=pending?`${pending.fields?.Time||""} — ${pending.fields?.Name||pending.fields?.Item||"Next item"}`:"Nothing pending";$("nextMeta").textContent=pending?.fields?.Date?new Date(pending.fields.Date+"T00:00:00").toLocaleDateString([], {weekday:"short",month:"short",day:"numeric"}):""}
function renderReminders(){const el=$("reminderList");el.innerHTML="";if(!state.reminders.length){el.innerHTML='<div class="muted">No reminders yet.</div>';return}state.reminders.forEach(x=>{const f=x.fields||{},done=f.Done===true,row=document.createElement("div");row.className="reminderRow";row.innerHTML=`<div class="planMain ${done?"done":""}"><b>${esc(f.Reminder||"Reminder")}</b><div class="muted">${esc(f.Type||"")} ${f.Interval?`· every ${esc(f.Interval)}`:""} ${f["Next Due"]?`· due ${esc(f["Next Due"])}`:""}</div>${f.Notes?`<div class="muted">${esc(f.Notes)}</div>`:""}</div><button class="small">${done?"Undo":"Done"}</button>`;row.querySelector("button").onclick=async()=>{try{await api("setReminderDone",{id:x.id,done:!done});await load()}catch(e){showError(e)}};el.appendChild(row)})}
function renderLoops(){const el=$("loopList");el.innerHTML="";if(!state.loops.length){el.innerHTML='<div class="muted">No completed loops recorded yet.</div>';return}[...state.loops].reverse().slice(0,50).forEach(x=>{const f=x.fields||{},row=document.createElement("div");row.className="loopRow";row.innerHTML=`<div class="planMain"><b>Loop ${esc(f["Loop #"]||"")}</b><div class="muted">${f["Loop Time"]?`Time: ${esc(f["Loop Time"])}`:""} ${f["Return Time"]?`· Returned ${new Date(f["Return Time"]).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}`:""}</div></div><b>${Number(f["Total Miles"]||0).toFixed(1)} mi</b>`;el.appendChild(row)})}
function renderNotes(){$("noteList").innerHTML=state.notes.slice(-30).reverse().map(x=>`<div class="muted" style="padding:10px 0;border-top:1px solid #e1edf2">${esc(x)}</div>`).join("")}
function switchTab(tab){activeTab=tab;document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.id===tab));window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
$("modeBtn").onclick=()=>{document.body.classList.toggle("runner");$("modeBtn").textContent=document.body.classList.contains("runner")?"CREW MODE":"RUNNER MODE"};
$("startBtn").onclick=async()=>{if(!confirm("Start the race now?\n\nThis starts the live race timer. If this is an accidental tap, choose Cancel."))return;try{await api("startRace");await load();switchTab("liveTab")}catch(e){showError(e)}};
$("resetBtn").onclick=async()=>{if(!confirm("Reset race to NOT STARTED?\n\nThis is for an accidental start. It will reset the current loop to 1 and keep your scheduled race start time."))return;try{await api("resetRace");await load()}catch(e){showError(e)}};
$("completeBtn").onclick=async()=>{if(!confirm("Mark the current loop complete?"))return;try{await api("completeLoop");await load()}catch(e){showError(e)}};
$("dnfBtn").onclick=async()=>{if(confirm("Mark the race DNF?"))try{await api("setStatus",{status:"DNF"});await load()}catch(e){showError(e)}};$("finishBtn").onclick=async()=>{if(confirm("Mark the race finished?"))try{await api("setStatus",{status:"Finished"});await load()}catch(e){showError(e)}};
$("addPlanBtn").onclick=()=>$("planDialog").showModal();$("planForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api("createPlan",{fields:{Date:f.get("date"),Time:f.get("time"),Name:f.get("name"),"Loop #":f.get("loop")?Number(f.get("loop")):null,Item:f.get("item"),Category:f.get("category"),Status:"Not started",Notes:f.get("notes"),Done:false}});e.target.reset();$("planDialog").close();await load()}catch(x){showError(x)}};
$("addReminderBtn").onclick=()=>$("reminderDialog").showModal();$("reminderForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api("createReminder",{fields:{Reminder:f.get("reminder"),Type:f.get("type"),Interval:f.get("interval")?Number(f.get("interval")):null,"Next Due":f.get("nextDue"),Notes:f.get("notes"),Done:false}});e.target.reset();$("reminderDialog").close();await load()}catch(x){showError(x)}};
$("saveNoteBtn").onclick=()=>{const v=$("noteInput").value.trim();if(!v)return;state.notes.push(new Date().toLocaleTimeString()+" — "+v);localStorage.setItem("backyardNotes",JSON.stringify(state.notes));$("noteInput").value="";renderNotes()};setInterval(()=>state.race&&render(),1000);load();